# ==============================================================================
# GLOBAL DEFAULT SETTINGS
# Models are auto-discovered from huggingface cache.
# ==============================================================================
[*]
ctx-size = 81920
mmap = 1
